### ISSUE TITLE
Swagger API specifications management

### ISSUE THREAD

**Issue by kshychko** [ausdigital/ausdigital-dcp#12]
As we decided to render swagger API spec in ausdigital.org for clear maintenance in github repos instead of one-way sync process in swaggerhub, we need to do the following:

- [x] 1. organise swagger.json files in spec repos - @kshychko
- [x] 2. add a render of spec to ausdigital.org - @webilhan 
- [x] 3. add a validation of swagger.json to build process - @kshychko

**Comment by kshychko** [comment]
> 1. organise swagger.json files in spec repos - @kshychko

Done. Now swagger.json exists in docs/%version% directory of a spec repo. For example:
https://github.com/ausdigital/ausdigital-dcp/blob/master/docs/1.0/swagger.json

Each swagger.json file is being copied to ausdigital.org repo to the corresponding directory.

@webilhan , please integrate swagger.json render into ausdigital.org. You may use https://jexhson.github.io/jekyll-swagger/#
Take into account that a path to json file is fixed, so probably a rendered spec should be available by the following url:
http://ausdigital.org/specs/ausdigital-bill/1.0/swagger-api
as the json file is available by the following url:
http://ausdigital.org/specs/ausdigital-bill/1.0/swagger.json

**Comment by monkeypants** [comment]
Do we need the word swagger in the url of the rendered page? What if instead of 
http://ausdigital.org/specs/ausdigital-bill/1.0/swagger-api we had 
http://ausdigital.org/specs/ausdigital-bill/1.0/api instead?

**Comment by kshychko** [comment]
I agree, better to go with /api. Updated the issue.

**Comment by monkeypants** [comment]
the spec render here is very nice:
https://dbc-loa1-idp.companybook.io/api/v0.0/#customers-get

@koriaf, how did you do it? Maybe we should use that for rendering all our specs everywhere.

**Comment by koriaf** [comment]
so, we don't use swaggerhub anymore?

**Comment by monkeypants** [comment]
@webilhan can you please briefly explain how it currently works and check if this ticket is up to date.

**Comment by kshychko** [comment]
spec repositories have been cleaned up
any API should be maintained now under the corresponding specification repository
path to swagger document - ausdigital-foo/docs/%version%/swagger.json
rendered API is available on ausidigital.org - http://ausdigital.org/specs/ausdigital-foo/%version%/api
for example - http://ausdigital.org/specs/ausdigital-dcp/1.0/api
validation results of swagger.json files are reported to [#api-monitoring](https://company-book.slack.com/messages/C4PNNCMTN/) slack channel.
@monkeypants please have a look and close the issue if everything is OK.

**Comment by monkeypants** [comment]
great!
