### ISSUE TITLE
swagger spec into repo

### ISSUE THREAD

**Issue by monkeypants** [ausdigital/ausdigital-dcp#3]
The swagger spec here https://swaggerhub.com/api/ausdigital/smp/0.1

should also be in the repo.

**Comment by onthebreeze** [comment]
yes.

The swagger spec are still configured (in swaggerhub) to push to
https://github.com/ausdigital/RESTful-framework/tree/master/APIs

That needs to be changed so that the right spec goes to the right repo and
we can then delete the "RESTful-framework" repo

**Comment by monkeypants** [comment]
OK, agree about merging/deleting RESTful-framework. RESTful is a quality, not a product :)

**Comment by monkeypants** [comment]
per #6, we also need to change the name of the swaggerhub resource

**Comment by monkeypants** [comment]
this was done ages ago (stale ticket)
